apiVersion: v1
kind: ConfigMap
metadata:
  name: mgmt-config
data:
  mgmt-config.cfg: |
    top; conf

    web-mgmt
      admin-state enabled
      local-address 0.0.0.0
      port 9090
    exit

    write mem
