apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - datapower-gitops-helloworld.yaml
  - dp-mgmt-service.yaml
  - dp-rest-mgmt-route.yaml
  - dp-web-mgmt-route.yaml
  - dp-xml-mgmt-route.yaml
