apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - datapower-service.yaml

  - service-mgmt.yaml
  
  - route-rest-mgmt.yaml
  - route-web-mgmt.yaml
  - route-xml-mgmt.yaml

  - cm-mgmt-config.yaml